"""Initial_migration

Revision ID: f513dfb87f05
Revises: 
Create Date: 2026-02-09 06:25:19.378298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f513dfb87f05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bronze_raw_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bronze_raw_data_source'), 'bronze_raw_data', ['source'], unique=False)
    op.create_table('gold_change_failure_rate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_deployments', sa.Integer(), nullable=True),
    sa.Column('failed_deployments', sa.Integer(), nullable=True),
    sa.Column('failure_rate_percent', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_change_failure_rate_repo_name'), 'gold_change_failure_rate', ['repo_name'], unique=False)
    op.create_table('gold_deployment_frequency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('deployment_count', sa.Integer(), nullable=True),
    sa.Column('frequency_per_day', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_deployment_frequency_repo_name'), 'gold_deployment_frequency', ['repo_name'], unique=False)
    op.create_table('gold_lead_time',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_lead_time_hours', sa.Float(), nullable=True),
    sa.Column('median_lead_time_hours', sa.Float(), nullable=True),
    sa.Column('p90_lead_time_hours', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_lead_time_repo_name'), 'gold_lead_time', ['repo_name'], unique=False)
    op.create_table('gold_mttr',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('avg_recovery_time_hours', sa.Float(), nullable=True),
    sa.Column('median_recovery_time_hours', sa.Float(), nullable=True),
    sa.Column('incident_count', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gold_mttr_repo_name'), 'gold_mttr', ['repo_name'], unique=False)
    op.create_table('silver_github_commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bronze_id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('sha', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('committed_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha')
    )
    op.create_index(op.f('ix_silver_github_commits_author'), 'silver_github_commits', ['author'], unique=False)
    op.create_index(op.f('ix_silver_github_commits_bronze_id'), 'silver_github_commits', ['bronze_id'], unique=False)
    op.create_index(op.f('ix_silver_github_commits_repo_name'), 'silver_github_commits', ['repo_name'], unique=False)
    op.create_table('silver_github_pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bronze_id', sa.UUID(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('created_at_source', sa.DateTime(), nullable=True),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('additions', sa.Integer(), nullable=True),
    sa.Column('deletions', sa.Integer(), nullable=True),
    sa.Column('changed_files', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_silver_github_pull_requests_author'), 'silver_github_pull_requests', ['author'], unique=False)
    op.create_index(op.f('ix_silver_github_pull_requests_bronze_id'), 'silver_github_pull_requests', ['bronze_id'], unique=False)
    op.create_index(op.f('ix_silver_github_pull_requests_repo_name'), 'silver_github_pull_requests', ['repo_name'], unique=False)
    op.create_table('silver_jira_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bronze_id', sa.UUID(), nullable=False),
    sa.Column('issue_key', sa.String(), nullable=False),
    sa.Column('project_key', sa.String(), nullable=False),
    sa.Column('issue_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('reporter', sa.String(), nullable=True),
    sa.Column('created_at_source', sa.DateTime(), nullable=True),
    sa.Column('updated_at_source', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('story_points', sa.Float(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issue_key')
    )
    op.create_index(op.f('ix_silver_jira_issues_assignee'), 'silver_jira_issues', ['assignee'], unique=False)
    op.create_index(op.f('ix_silver_jira_issues_bronze_id'), 'silver_jira_issues', ['bronze_id'], unique=False)
    op.create_index(op.f('ix_silver_jira_issues_project_key'), 'silver_jira_issues', ['project_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_silver_jira_issues_project_key'), table_name='silver_jira_issues')
    op.drop_index(op.f('ix_silver_jira_issues_bronze_id'), table_name='silver_jira_issues')
    op.drop_index(op.f('ix_silver_jira_issues_assignee'), table_name='silver_jira_issues')
    op.drop_table('silver_jira_issues')
    op.drop_index(op.f('ix_silver_github_pull_requests_repo_name'), table_name='silver_github_pull_requests')
    op.drop_index(op.f('ix_silver_github_pull_requests_bronze_id'), table_name='silver_github_pull_requests')
    op.drop_index(op.f('ix_silver_github_pull_requests_author'), table_name='silver_github_pull_requests')
    op.drop_table('silver_github_pull_requests')
    op.drop_index(op.f('ix_silver_github_commits_repo_name'), table_name='silver_github_commits')
    op.drop_index(op.f('ix_silver_github_commits_bronze_id'), table_name='silver_github_commits')
    op.drop_index(op.f('ix_silver_github_commits_author'), table_name='silver_github_commits')
    op.drop_table('silver_github_commits')
    op.drop_index(op.f('ix_gold_mttr_repo_name'), table_name='gold_mttr')
    op.drop_table('gold_mttr')
    op.drop_index(op.f('ix_gold_lead_time_repo_name'), table_name='gold_lead_time')
    op.drop_table('gold_lead_time')
    op.drop_index(op.f('ix_gold_deployment_frequency_repo_name'), table_name='gold_deployment_frequency')
    op.drop_table('gold_deployment_frequency')
    op.drop_index(op.f('ix_gold_change_failure_rate_repo_name'), table_name='gold_change_failure_rate')
    op.drop_table('gold_change_failure_rate')
    op.drop_index(op.f('ix_bronze_raw_data_source'), table_name='bronze_raw_data')
    op.drop_table('bronze_raw_data')
    # ### end Alembic commands ###
